{ pkgs, ... }: {
  home.packages = with pkgs; [
    amdgpu_top
    android-studio
    ckan
    vesktop
    eyedropper
    fragments
    #ghostty
    gimp
    gnome-boxes
    gnome-color-manager
    gnome-power-manager
    gnomeExtensions.appindicator
    gnomeExtensions.blur-my-shell
    gnomeExtensions.bluetooth-battery-meter
    gnomeExtensions.clipboard-indicator
    gnomeExtensions.dash-to-dock
    gnomeExtensions.desktop-cube
    gnomeExtensions.fuzzy-app-search
    gnomeExtensions.fullscreen-notifications
    gnomeExtensions.gsconnect
    gnomeExtensions.lockscreen-extension
    gnomeExtensions.media-progress
    gnomeExtensions.pip-on-top
    gnomeExtensions.privacy-settings-menu
    gnomeExtensions.user-avatar-in-quick-settings
    gnomeExtensions.system-monitor
    godot_4
    gtk4
    mangohud
    papers
    qgnomeplatform
    qgnomeplatform-qt6
    ungoogled-chromium
    vlc
    wine64
    wl-clipboard
  ];
}
